### ISSUE TITLE
How to setup my local machine to be able to run this Project?

### ISSUE THREAD

**Issue by controlade** [allan-vega/Python#1]
## Issue
I want to run this project's python scripts in my local development environment (a.k.a. my laptop)

## Job to be Done
@allan-vega   please document in this issue the procedure I have to follow to be able to run and test the python scripts.
Please be as explicit and detailed as possible.

**Comment by allan-vega** [comment]
[How can I run python project.pdf](https://github.com/allan-vega/Python/files/8313178/How.can.I.run.python.project.pdf)
Hi Alberto this is how you can run python's project, have a good night. Best regards.

**Comment by controlade** [comment]
> [How can I run python project.pdf](https://github.com/allan-vega/Python/files/8313178/How.can.I.run.python.project.pdf) Hi Alberto this is how you can run python's project, have a good night. Best regards.

Great answer!
Thanks.

**Comment by controlade** [comment]
Now that you have given the resolution of this issue I will proceed to close it.
